import './style.css';

const app = document.querySelector<HTMLDivElement>('#app')!;
const API = '/api';
const PRODUCT = 'Quote Approval Receipt';
const SLUG = 'quote-approval-receipt';
const BILLING = `https://api.sociobot.in/api/v1/products/${SLUG}`;
const money = (n: number, currency = 'USD') => new Intl.NumberFormat(undefined, { style: 'currency', currency }).format(n);
const escapeHtml = (value: unknown) => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]!));
const formatDate = (value: string) => new Intl.DateTimeFormat(undefined, { year:'numeric', month:'short', day:'numeric', hour:'2-digit', minute:'2-digit', timeZoneName:'short' }).format(new Date(value));

type LineItem = { description: string; quantity: number; rate: number };
type Quote = { id:string; creator_name:string; business_name:string; quote_number:string; client_name:string; currency:string; summary:string; items:LineItem[]; subtotal:number; tax:number; total:number; consent_text:string; created_at:string; expires_at:string; decided:boolean; demo:boolean };
type Receipt = { receipt:{id:string;approver_name:string;approver_title:string;approver_email?:string;decision:string;note?:string;consent_text:string;decided_at:string;snapshot_hash:string};quote:Quote;pdf_path:string };

function shell(content: string, opts: {demo?: boolean; compact?: boolean} = {}) {
  const nav = opts.compact ? '' : `<nav aria-label="Main navigation"><a href="/demo" data-link>Demo</a><a href="/new" data-link>Make a link</a><a href="/privacy" data-link>Privacy</a></nav>`;
  app.innerHTML = `
    ${opts.demo ? `<aside class="demo-bar" aria-label="Demo mode"><strong>Demo — sample data, nothing is saved to your records</strong><span><button class="text-button" id="reset-demo">Reset demo</button><a href="/new" data-link>Start for real</a></span></aside>` : ''}
    <header class="site-header"><a class="wordmark" href="/" data-link aria-label="Quote Approval Receipt home"><span class="reel" aria-hidden="true"></span><span>Quote approval<br>receipt</span></a>${nav}</header>
    <main id="main" tabindex="-1">${content}</main>
    <div class="route-status" aria-live="polite" aria-atomic="true"></div>
    <footer><p>Named quote decisions, kept with the quote.</p><nav aria-label="Footer"><a href="/privacy" data-link>Privacy</a><a href="/terms" data-link>Terms</a><a href="https://sociobot.in" rel="external">Built by Param Factory <span class="sr-only">(external site)</span></a></nav><p class="fine">v1.0 · Original generated artwork</p></footer>`;
  document.querySelector('h1')?.setAttribute('tabindex', '-1');
  bindLinks();
  document.querySelector('#reset-demo')?.addEventListener('click', () => renderDemo(true));
}

function pageMeta(title: string, description: string, noindex = false) {
  document.title = title;
  document.querySelector('meta[name="description"]')?.setAttribute('content', description);
  document.querySelector('link[rel="canonical"]')?.setAttribute('href', `https://quote-approval-receipt.sociobot.in${location.pathname}`);
  let robots = document.querySelector<HTMLMetaElement>('meta[name="robots"]');
  if (!robots) { robots = document.createElement('meta'); robots.name = 'robots'; document.head.append(robots); }
  robots.content = noindex ? 'noindex,nofollow,noarchive' : 'index,follow';
}

function bindLinks() {
  document.querySelectorAll<HTMLAnchorElement>('a[data-link]').forEach(link => link.addEventListener('click', e => {
    if (e.button === 0 && !e.metaKey && !e.ctrlKey && !e.shiftKey) { e.preventDefault(); navigate(link.pathname); }
  }));
}

function navigate(path: string) { history.pushState({}, '', path); route(true); }
window.addEventListener('popstate', () => route(true));

function facts() { return `<ul class="facts" aria-label="Key facts"><li><strong>Free:</strong> 30-day link retention</li><li><strong>Private:</strong> delete or export each record</li><li><strong>Clear:</strong> PDF receipt after a decision</li></ul>`; }

function landing() {
  pageMeta('Quote Approval Receipt — Record quote decisions', 'Capture who approved a fixed quote and issue a timestamped PDF receipt.');
  shell(`
    <section class="hero torn">
      <div class="hero-copy"><p class="eyebrow">A small record for a costly “who said yes?”</p><h1>Record who approved your quote</h1><p class="lede">For contractors whose client approves by email or chat, then changes expectations later.</p>
        <div class="hero-action"><a class="button primary" href="/demo" data-link>Try it with sample data</a><span>Loads a private sample quote. Nothing enters your records.</span></div>${facts()}</div>
      <figure class="hero-art"><img src="/quote-cassette.webp" width="900" height="600" alt="A cassette holding quote sheets beside a red approval stamp." fetchpriority="high" decoding="async"><figcaption>Fix the quote. Name the decision maker. Keep the receipt.</figcaption></figure>
    </section>
    <section class="workbench" aria-labelledby="preview-title"><div class="section-label">Live preview / side A</div><div><h2 id="preview-title">Turn an existing quote into one clear link</h2><p>Paste the agreed scope and totals. The link freezes that snapshot.</p><a class="button secondary" href="/new" data-link>Make an approval link</a></div><div class="mini-receipt" aria-label="Example approval receipt"><span class="stamp">Approved</span><p>QUOTE NS-2048</p><strong>Juniper Market</strong><p>Mara Chen · Brand director</p><p>18 Aug 2026 · 14:32 UTC</p><code>proof 92dc…41a</code></div></section>
    <section class="how" aria-labelledby="how-title"><div class="section-label">Three tracks</div><h2 id="how-title">How the record gets made</h2><ol><li><b>01 / Freeze</b><span>Enter the quote details you already agreed.</span></li><li><b>02 / Send</b><span>Share the private link with the client contact.</span></li><li><b>03 / Keep</b><span>Download the named decision and fixed snapshot.</span></li></ol></section>
    <section class="limits torn" aria-labelledby="limits-title"><div><p class="eyebrow">What it does not do</p><h2 id="limits-title">Proof of a decision, not an e-signature</h2></div><div><p>This is not proposal software or a regulated signature service.</p><p>It records the words, person, time, and fixed quote snapshot.</p><p>We store the approver details needed for that record. No tracking scripts run here.</p></div></section>
    <section class="price" aria-labelledby="price-title"><div class="price-tape" aria-hidden="true">Studio tape</div><div><p class="eyebrow">For teams that keep records longer</p><h2 id="price-title">Keep receipts for one year</h2><p><strong>$29 once.</strong> Studio adds 365-day retention. The free tier keeps 30 days.</p><a class="button primary" href="${BILLING}/checkout">Buy Studio for $29</a><button class="text-button" id="restore-license">Have a license? Paste it</button><p class="fine">Sociobot/Dodo is the merchant of record. Refunds are handled there.</p><div id="license-area" aria-live="polite"></div></div></section>`);
  document.querySelector('#restore-license')?.addEventListener('click', showLicenseField);
  handleLicenseReturn();
}

function quotePaper(q: Quote) {
  return `<article class="quote-paper" aria-label="Quote ${escapeHtml(q.quote_number)}"><header><div><span>Quote</span><strong>${escapeHtml(q.quote_number)}</strong></div><div class="right"><span>From</span><strong>${escapeHtml(q.business_name)}</strong></div></header><div class="quote-to"><span>Prepared for</span><strong>${escapeHtml(q.client_name)}</strong></div><p class="scope">${escapeHtml(q.summary)}</p><div class="item-list">${q.items.map(i => `<div><span>${escapeHtml(i.description)} <small>${i.quantity} × ${money(i.rate,q.currency)}</small></span><b>${money(i.quantity*i.rate,q.currency)}</b></div>`).join('')}</div><dl class="totals"><div><dt>Subtotal</dt><dd>${money(q.subtotal,q.currency)}</dd></div>${q.tax ? `<div><dt>Tax</dt><dd>${money(q.tax,q.currency)}</dd></div>`:''}<div class="grand"><dt>Total</dt><dd>${money(q.total,q.currency)}</dd></div></dl><footer>Fixed ${formatDate(q.created_at)}</footer></article>`;
}

async function approvalScreen(q: Quote, token: string, workspace?: string) {
  pageMeta(`${workspace?'Demo':'Review quote'} — ${PRODUCT}`, `Review quote ${q.quote_number} and record a named decision.`, true);
  shell(`<section class="approval-head"><p class="eyebrow">Decision requested by ${escapeHtml(q.creator_name)}</p><h1>Review and decide on this quote</h1><p>Check the fixed snapshot before you record a decision.</p></section><div class="approval-layout">${quotePaper(q)}<section class="decision-panel" aria-labelledby="decision-title">${q.decided ? `<h2 id="decision-title">A decision is already recorded</h2><p>This quote cannot accept another decision.</p>` : `<h2 id="decision-title">Name the decision maker</h2><form id="decision-form" novalidate><label>Full name <input name="name" required minlength="2" maxlength="100" autocomplete="name" value="${workspace?'Mara Chen':''}"></label><label>Job title <input name="title" required minlength="2" maxlength="100" autocomplete="organization-title" value="${workspace?'Brand director':''}"></label><label>Email <span class="optional">optional</span><input name="email" type="email" maxlength="160" autocomplete="email"></label><label>Note <span class="optional">optional</span><textarea name="note" maxlength="1000" rows="3" placeholder="Name the change you need."></textarea></label><fieldset><legend>Choose one decision</legend><label class="choice approve"><input type="radio" name="decision" value="approved" required> Approve quote</label><label class="choice changes"><input type="radio" name="decision" value="changes_requested"> Request changes</label></fieldset><label class="consent"><input type="checkbox" name="consent" required> <span>${escapeHtml(q.consent_text)}</span></label><div class="form-error" id="form-error" role="alert"></div><button class="button primary full" type="submit">Record this decision</button><p class="fine">This action is final. It records your name, title, decision, time, browser details, and a one-way network-address hash.</p></form>`}</section></div>`, {demo: Boolean(workspace), compact: !workspace});
  const form = document.querySelector<HTMLFormElement>('#decision-form');
  form?.addEventListener('submit', async e => {
    e.preventDefault(); const error = document.querySelector<HTMLDivElement>('#form-error')!;
    if (!form.reportValidity()) { error.textContent='Complete each required field, then record the decision.'; return; }
    const data = Object.fromEntries(new FormData(form));
    const body = {name:data.name,title:data.title,email:data.email||null,note:data.note||null,decision:data.decision,consent:data.consent==='on',...(workspace?{workspace}:{})};
    const button=form.querySelector<HTMLButtonElement>('button[type=submit]')!;button.disabled=true;button.textContent='Recording decision…';
    try { const result=await request<Receipt>(workspace?`${API}/demo/${workspace}/decision`:`${API}/share/${token}/decision`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}); sessionStorage.setItem(`receipt:${result.receipt.id}`,JSON.stringify(result)); history.replaceState({},'',`/receipt/${result.receipt.id}${workspace?'?demo=1':''}`); receiptScreen(result,Boolean(workspace)); }
    catch(err){error.textContent=errorMessage(err);button.disabled=false;button.textContent='Record this decision';}
  });
}

function newQuote() {
  pageMeta(`Make an approval link — ${PRODUCT}`, 'Enter an existing quote and create a private decision link.', true);
  const studio = licenseValid();
  shell(`<section class="builder-head"><p class="eyebrow">New quote snapshot / side A</p><h1>Make a quote approval link</h1><p>Enter the quote you already prepared. We freeze these details.</p></section><form class="builder" id="quote-form" novalidate><section><h2>Who is sending this?</h2><div class="grid-2"><label>Your name<input name="creator_name" required minlength="2" maxlength="100" autocomplete="name"></label><label>Business name<input name="business_name" required minlength="2" maxlength="120" autocomplete="organization"></label></div></section><section><h2>Which quote is this?</h2><div class="grid-2"><label>Quote number<input name="quote_number" required maxlength="60"></label><label>Client name<input name="client_name" required minlength="2" maxlength="120"></label></div><label>Scope summary<textarea name="summary" required minlength="4" maxlength="2000" rows="4"></textarea></label></section><section><h2>What does it cost?</h2><div id="items"><div class="item-row"><label>Description<input name="description" value="Project work" required maxlength="160"></label><label>Quantity<input name="quantity" type="number" value="1" min="0.01" step="0.01" required></label><label>Rate<input name="rate" type="number" min="0" step="0.01" required></label><button type="button" class="remove-item" aria-label="Remove this item">×</button></div></div><button type="button" class="text-button" id="add-item">+ Add another item</button><div class="grid-2"><label>Currency<select name="currency"><option>USD</option><option>EUR</option><option>GBP</option><option>CAD</option><option>AUD</option><option>INR</option></select></label><label>Tax percent<input name="tax_percent" type="number" min="0" max="100" step="0.01" value="0"></label></div></section><section><h2>What must the approver confirm?</h2><label>Consent text<textarea name="consent_text" required minlength="12" maxlength="500" rows="3">I confirm that I am authorised to make this decision for the client named above.</textarea></label><p class="fine">Edit this wording to match how your business asks for consent.</p></section><section class="retention"><h2>How long should we keep it?</h2><label class="choice"><input type="radio" name="retention_days" value="30" ${!studio?'checked':''}> 30 days · free</label><label class="choice"><input type="radio" name="retention_days" value="365" ${studio?'checked':''} ${studio?'':'disabled'}> 365 days · Studio ${studio?'active':'license required'}</label></section><div class="form-error" id="form-error" role="alert"></div><button class="button primary" type="submit">Create private approval link</button></form>`);
  const items=document.querySelector('#items')!;
  const bindRemove=()=>document.querySelectorAll<HTMLButtonElement>('.remove-item').forEach(b=>b.onclick=()=>{if(items.children.length>1)b.closest('.item-row')?.remove();});bindRemove();
  document.querySelector('#add-item')?.addEventListener('click',()=>{items.insertAdjacentHTML('beforeend',`<div class="item-row"><label>Description<input name="description" required maxlength="160"></label><label>Quantity<input name="quantity" type="number" value="1" min="0.01" step="0.01" required></label><label>Rate<input name="rate" type="number" min="0" step="0.01" required></label><button type="button" class="remove-item" aria-label="Remove this item">×</button></div>`);bindRemove();});
  const form=document.querySelector<HTMLFormElement>('#quote-form')!;form.addEventListener('submit',async e=>{e.preventDefault();const error=document.querySelector<HTMLDivElement>('#form-error')!;if(!form.reportValidity()){error.textContent='Complete each required quote field, then create the link.';return;}const fd=new FormData(form);const descriptions=fd.getAll('description');const quantities=fd.getAll('quantity');const rates=fd.getAll('rate');const payload={creator_name:fd.get('creator_name'),business_name:fd.get('business_name'),quote_number:fd.get('quote_number'),client_name:fd.get('client_name'),summary:fd.get('summary'),currency:fd.get('currency'),tax_percent:Number(fd.get('tax_percent')),consent_text:fd.get('consent_text'),retention_days:Number(fd.get('retention_days')),items:descriptions.map((d,i)=>({description:d,quantity:Number(quantities[i]),rate:Number(rates[i])}))};const button=form.querySelector<HTMLButtonElement>('button[type=submit]')!;button.disabled=true;button.textContent='Creating link…';try{const made=await request<{id:string;owner_token:string;share_path:string;expires_at:string}>(`${API}/quotes`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});localStorage.setItem(`owner:${made.id}`,made.owner_token);localStorage.setItem('last-quote',made.id);createdScreen(made);}catch(err){error.textContent=errorMessage(err);button.disabled=false;button.textContent='Create private approval link';}});
}

function createdScreen(made:{id:string;share_path:string;expires_at:string}) {
  pageMeta(`Link ready — ${PRODUCT}`,'Copy the private quote approval link.',true);
  const url=`${location.origin}${made.share_path}`;
  shell(`<section class="success-screen torn"><span class="stamp">Ready</span><p class="eyebrow">The quote snapshot is fixed</p><h1>Your approval link is ready</h1><p>Send this link to the person who can approve the quote.</p><label>Private approval link<div class="copy-field"><input id="share-url" readonly value="${escapeHtml(url)}"><button class="button secondary" id="copy-link">Copy link</button></div></label><p class="fine">The link expires ${formatDate(made.expires_at)}. Search engines are told not to index it.</p><a class="button primary" href="/manage/${made.id}" data-link>View quote status</a></section>`);
  document.querySelector('#copy-link')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(url);const b=document.querySelector<HTMLButtonElement>('#copy-link')!;b.textContent='Copied';});
}

async function manageScreen(id:string){pageMeta(`Quote status — ${PRODUCT}`,'Check a quote decision, export its record, or delete it.',true);const key=localStorage.getItem(`owner:${id}`);if(!key){errorPage('This management key is missing','Open the link on the device that created the quote.');return;}loading('Loading quote status…');try{const q=await request<Quote>(`${API}/quotes/${id}`,{headers:{'x-owner-token':key}});shell(`<section class="manage"><p class="eyebrow">Quote ${escapeHtml(q.quote_number)}</p><h1>${q.decided?'A decision is recorded':'Waiting for a decision'}</h1><p>${q.decided?'Open the approval link to see the recorded receipt.':'Share the approval link with the named client contact.'}</p>${quotePaper(q)}<div class="manage-actions"><a class="button secondary" href="${API}/quotes/${id}/export" id="export-record">Export record as JSON</a><button class="button danger" id="delete-record">Delete this record</button></div><p class="fine">Expires ${formatDate(q.expires_at)}.</p></section>`);document.querySelector('#export-record')?.addEventListener('click',async e=>{e.preventDefault();const res=await fetch(`${API}/quotes/${id}/export`,{headers:{'x-owner-token':key}});const blob=await res.blob();downloadBlob(blob,'quote-record.json');});document.querySelector('#delete-record')?.addEventListener('click',async()=>{if(!confirm(`Delete quote ${q.quote_number} and its receipt? This cannot be undone.`))return;await request(`${API}/quotes/${id}`,{method:'DELETE',headers:{'x-owner-token':key}});localStorage.removeItem(`owner:${id}`);shell(`<section class="success-screen"><h1>The quote record was deleted</h1><p>The approval link and receipt no longer work.</p><a class="button primary" href="/new" data-link>Make another link</a></section>`);});}catch(err){errorPage('The quote could not be loaded',errorMessage(err));}}

async function renderDemo(reset=false){pageMeta(`Demo — ${PRODUCT}`,'Try a sample quote decision in an isolated demo.',true);loading('Loading the sample quote…',true);try{if(reset)sessionStorage.removeItem('demo:workspace');let demo=sessionStorage.getItem('demo:workspace');let data:{workspace:string;quote:{public_token:string}};if(!demo){data=await request(`${API}/demo`,{method:'POST'});sessionStorage.setItem('demo:workspace',JSON.stringify(data));}else data=JSON.parse(demo);const q=await request<Quote>(`${API}/share/${data.quote.public_token}`);approvalScreen(q,data.quote.public_token,data.workspace);}catch(err){errorPage('The demo could not start',`${errorMessage(err)} Reset the demo to try again.`,true);}}

function receiptScreen(data:Receipt,demo=false){pageMeta(`Receipt ${data.quote.quote_number} — ${PRODUCT}`,'View a timestamped quote decision receipt.',true);const approved=data.receipt.decision==='approved';shell(`<section class="receipt-screen"><div class="receipt-title"><span class="stamp ${approved?'':'change-stamp'}">${approved?'Approved':'Changes requested'}</span><p class="eyebrow">Decision receipt / side B</p><h1>${approved?'This quote was approved':'Changes were requested'}</h1><p>Recorded ${formatDate(data.receipt.decided_at)}</p></div><article class="receipt torn"><div><span>Quote</span><strong>${escapeHtml(data.quote.quote_number)}</strong></div><div><span>Decision maker</span><strong>${escapeHtml(data.receipt.approver_name)}</strong><small>${escapeHtml(data.receipt.approver_title)}</small></div><div><span>Client</span><strong>${escapeHtml(data.quote.client_name)}</strong></div><div><span>Total</span><strong>${money(data.quote.total,data.quote.currency)}</strong></div>${data.receipt.note?`<div class="wide"><span>Note</span><p>${escapeHtml(data.receipt.note)}</p></div>`:''}<div class="wide"><span>Consent recorded</span><p>${escapeHtml(data.receipt.consent_text)}</p></div><div class="wide proof"><span>Snapshot hash</span><code>${escapeHtml(data.receipt.snapshot_hash)}</code></div></article><div class="receipt-actions"><a class="button primary" href="${data.pdf_path}" download>Download PDF receipt</a>${demo?'<button class="button secondary" id="reset-demo">Reset demo</button>':''}</div><details><summary>View the fixed quote snapshot</summary>${quotePaper(data.quote)}</details></section>`,{demo,compact:!demo});document.querySelector('#reset-demo')?.addEventListener('click',()=>renderDemo(true));}

async function loadReceipt(id:string){const cached=sessionStorage.getItem(`receipt:${id}`);if(cached){receiptScreen(JSON.parse(cached),new URLSearchParams(location.search).has('demo'));return;}loading('Loading receipt…');try{receiptScreen(await request<Receipt>(`${API}/receipts/${id}`),false);}catch(err){errorPage('The receipt could not be loaded',errorMessage(err));}}

function legal(kind:'privacy'|'terms') {const privacy=kind==='privacy';pageMeta(`${privacy?'Privacy':'Terms'} — ${PRODUCT}`,privacy?'What quote and approver data we store and how to remove it.':'Terms for using Quote Approval Receipt.');shell(`<article class="legal"><p class="eyebrow">${privacy?'Your data':'Use terms'} / plain copy</p><h1>${privacy?'Privacy that fits the record':'Terms for clear quote records'}</h1>${privacy?`<h2>What we store</h2><p>We store the quote snapshot, sender name, business name, and client name.</p><p>After a decision, we store the approver name, title, optional email, note, time, browser details, and a one-way network-address hash.</p><h2>Why we store it</h2><p>These details make the approval record useful to both sides.</p><h2>How long we keep it</h2><p>Free records expire after 30 days. Studio records expire after 365 days.</p><p>Demo workspaces expire after 24 hours and stay separate from real records.</p><h2>Your choices</h2><p>The sender can export or delete a record from its management link.</p><p>For a request you cannot complete there, email <a href="mailto:privacy@sociobot.in">privacy@sociobot.in</a>.</p><h2>Payments and tracking</h2><p>We do not run analytics or advertising scripts.</p><p>Sociobot/Dodo handles Studio checkout under its own privacy terms.</p>`:`<h2>What this service provides</h2><p>The service records a named decision against a fixed quote snapshot.</p><p>It does not provide legal advice or a regulated electronic signature.</p><h2>Your responsibility</h2><p>Only upload quote details you may share with the intended client.</p><p>Use consent words that fit your business and local rules.</p><h2>Availability</h2><p>Keep your exported receipt. We may change or stop the service.</p><h2>Studio purchase</h2><p>Studio costs $29 once and adds 365-day retention.</p><p>Sociobot/Dodo is the merchant of record. A refund revokes the license.</p><h2>Contact</h2><p>Email <a href="mailto:support@sociobot.in">support@sociobot.in</a> with service questions.</p>`}<p class="fine">Effective 28 August 2026.</p></article>`);}

function notFound(){pageMeta(`Not found — ${PRODUCT}`,'The requested page was not found.',true);shell(`<section class="not-found"><div class="broken-tape" aria-hidden="true"><span></span><span></span></div><p class="eyebrow">Tape ended / 404</p><h1>This page is not on the record</h1><p>The link may be mistyped, expired, or deleted.</p><a class="button primary" href="/" data-link>Return home</a></section>`);}
function loading(message:string,demo=false){shell(`<section class="loading"><div class="spinner" aria-hidden="true"></div><h1>${escapeHtml(message)}</h1><p>Keep this page open.</p></section>`,{demo});}
function errorPage(title:string,message:string,demo=false){pageMeta(`Error — ${PRODUCT}`,message,true);shell(`<section class="error-page"><p class="eyebrow">The tape snagged</p><h1>${escapeHtml(title)}</h1><p>${escapeHtml(message)}</p><a class="button primary" href="${demo?'/demo':'/'}" data-link>${demo?'Reset the demo':'Return home'}</a></section>`,{demo});}
function errorMessage(err:unknown){return err instanceof Error?err.message:'The request failed. Check your connection and try again.';}
async function request<T=unknown>(url:string,init?:RequestInit):Promise<T>{let res:Response;try{res=await fetch(url,init);}catch{throw new Error('The service could not be reached. Check your connection and try again.');}if(!res.ok){const data=await res.json().catch(()=>({error:`The service returned ${res.status}. Try again.`}));throw new Error(data.error);}if(res.status===204)return undefined as T;return res.json();}
function downloadBlob(blob:Blob,name:string){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}

function licenseValid(){try{const cache=JSON.parse(localStorage.getItem(`sb_license_verdict:${SLUG}`)||'null');return Boolean(cache?.valid&&Date.now()-cache.checked_at<86400000);}catch{return false;}}
function handleLicenseReturn(){const params=new URLSearchParams(location.search);const token=params.get('license');if(token){localStorage.setItem(`sb_license:${SLUG}`,token);params.delete('license');history.replaceState({},'',`${location.pathname}${params.size?'?'+params:''}`);verifyLicense(token);}else{const saved=localStorage.getItem(`sb_license:${SLUG}`);if(saved&&(!licenseValid()))verifyLicense(saved);}}
function showLicenseField(){const area=document.querySelector<HTMLDivElement>('#license-area')!;area.innerHTML=`<form id="license-form" class="license-form"><label>License token<input name="license" required autocomplete="off"></label><button class="button secondary">Verify license</button></form>`;area.querySelector('form')?.addEventListener('submit',e=>{e.preventDefault();const token=new FormData(e.currentTarget as HTMLFormElement).get('license') as string;localStorage.setItem(`sb_license:${SLUG}`,token.trim());verifyLicense(token.trim());});}
async function verifyLicense(token:string){const area=document.querySelector<HTMLDivElement>('#license-area');if(area)area.textContent='Checking license…';try{const result=await request<{valid:boolean;reason:string}>(`${BILLING}/verify?license=${encodeURIComponent(token)}`);localStorage.setItem(`sb_license_verdict:${SLUG}`,JSON.stringify({...result,checked_at:Date.now()}));if(area)area.innerHTML=result.valid?'<p class="license-good">Studio is active on this device.</p>':`<p>License no longer active (${escapeHtml(result.reason)}). <a href="${BILLING}/checkout">Buy Studio</a>.</p>`;}catch{if(area)area.textContent=licenseValid()?'Studio stays active from the last check.':'The license could not be checked. Try again when online.';}}

async function route(focus=false){const path=location.pathname;try{if(path==='/')landing();else if(path==='/new')newQuote();else if(path==='/demo')await renderDemo();else if(path==='/privacy')legal('privacy');else if(path==='/terms')legal('terms');else if(path.startsWith('/approve/')){loading('Loading the fixed quote…');const token=path.split('/')[2];approvalScreen(await request<Quote>(`${API}/share/${token}`),token);}else if(path.startsWith('/receipt/'))await loadReceipt(path.split('/')[2]);else if(path.startsWith('/manage/'))await manageScreen(path.split('/')[2]);else notFound();}catch(err){errorPage('This page could not be loaded',errorMessage(err));}if(focus){window.scrollTo(0,0);requestAnimationFrame(()=>{document.querySelector<HTMLElement>('h1')?.focus({preventScroll:true});document.querySelector('.route-status')!.textContent=document.querySelector('h1')?.textContent||'';});}}

route();
